### ISSUE TITLE
Watcher not working in Docker even with `tty:true`

### ISSUE THREAD

**Issue by dseravalli** [rails/tailwindcss-rails#320]
The CSS is built successfully when I first `docker-compose up` but doesn't rebuild when I edit and save files.

Rails 7.0.4.3
tailwindcss-rails 2.0.29
MacOS Sonoma 14.2
Orbstack 1.3.0

tailwind.config.js content
```js
  content: [
    './public/*.html',
    './app/helpers/**/*.rb',
    './app/javascript/**/*.js',
    './app/views/**/*.{erb,haml,html,slim}',
    './node_modules/flowbite/**/*.js',
  ],
```

docker-compose
```yaml
version: '3.9'
services:
  app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3000'
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - rails
...
```

Dockerfile.dev
```
...
CMD ["./bin/dev"]
```

Procfile.dev
```
web: bin/rails server -p 3000 -b 0.0.0.0
css: bin/rails tailwindcss:watch
```

/bin/dev
```
#!/usr/bin/env sh

if ! gem list foreman -i --silent; then
  echo "Installing foreman..."
  gem install foreman
fi

exec foreman start -f Procfile.dev "$@"
```
