### ISSUE TITLE
Support Tailwind's theme() function in asset pipeline CSS files

### ISSUE THREAD

**Issue by pas256** [rails/tailwindcss-rails#378]
TailwindCSS has this neat function called [`theme()`](https://tailwindcss.com/docs/functions-and-directives#theme) which lets you do things like

```css
.btn-blue {
  background-color: theme(colors.blue.500);
}
```

but it doesn't seem to work with this gem. I've tried the above in `app/assets/stylesheets/application.css` but no dice. I suspect it is because of Sprokets or the asset pipeline in some way, but am far from an expert at it. I'm using a Rails 7.1.
